language: ruby
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without=development"
before_install: gem update --system
matrix:
  include:
  - rvm: 2.4.0
    env: PUPPET_VERSION='~> 4.9.0'
    script: bundle exec rake test
